apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-elasticsearch-es-default-0
  namespace: eck
  labels:
    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-sa
  namespace: eck
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elasticsearch-sa-binding
  namespace: eck
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: elasticsearch
subjects:
  - kind: ServiceAccount
    name: elasticsearch-sa
    namespace: eck