apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-pod-patch-role
  namespace: argo-workflows
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch", "delete"]