apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-gp3
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.ebs.csi.aws.com/zone
    values: ["<<AVAILABILITY_ZONE>>"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: storage-gp3
  resources:
    requests:
      storage: 4Gi
