---
apiVersion: v1
kind: Service
metadata:
  name: "backend-test-svc"
  namespace: {{ .Release.Namespace }}
  labels:
    app: nginx-test
  annotations:
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook": test
spec:
  selector:
    app: nginx-test
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: ClusterIP