## Added to upstream chart to support certficate creation
{{ if .Values.lookUpCertificate.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.lookUpCertificate.secretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls

data:
{{- with lookup "v1" "Secret" (.Values.lookUpCertificate.namespace | default "istio-system" )  .Values.lookUpCertificate.secretName }}
    {{ range $k, $v := .data }}
      {{ $k }}: {{ $v }}
    {{ end }}
{{- end }}
{{ end }}
